---
title: "About me"
website:
  toc: true
---

## Experience

Here is a resume of my education and working experiences.

### Actual Work

#### Actuary Pricing Motor

My current job is based in Trieste, my hometown. I work at Allianz as an actuary in the motor pricing team.
Together with my team, I am responsible for developing the technical and tariff models for the motor sector of the Italian branch.

### Past Work Positions

During my master I worked in jobs related to my field of studies. Before, I was working in different backgrounds which helped me to grow  cross-functionally 

#### Actuary - Internship

My internship took place at Munich, Germappny, in one of the world's leading insurance and financial services providers. I worked for 6 months at Allianz SE, holding company of Allianz Group, in the H2 department, related to the finance processes. Specifically, I worked in the Group Actuarial Non-Life team, responsible for the Actuarial Function of the company, which is the team in charge of risk assessment, financial modeling, regulatory compliance, and strategic planning.

In my case, I was dedicated to:

-   Contributing to the team's reporting products. Mainly Inflation Reserve and Group Reserve Committee;

-   Testing new Reserve Reviewing approaches in ResQ, in particular, Bootstrapping for DFMs and Stochastic Result Selection to deal with confidence intervals for the ultimate claims;

-   Working on an internal project aiming to build and disclose a new model, developed in R, in order to properly assess implicit inflation in Run-Off triangles; in collaboration with one of the companies of the Group;

-   Support in building tools to facilitate and develop day-to-day processes;

-   Automatizing core reporting processes, by bridging data flow from SAP, Excel, and Word Implementation in VBA.

#### Biostatistician

From August 2023 to December 2024, I was involved in national medical research where I was in charge of the statistical part. The topic was *"Education in lower and upper secondary schools and support of the network of reference figures for youth for prevention of HPV and other sexually transmitted infections".*

My tasks were:

-   Analyzing surveys via R and building reports for the different geographic areas and school levels;

-   Building reports which contained stratified frequency tables, charts, models and statistical tests;

-   Writing the methodologic analysis in research papers.

The models built were GLM (generalized linear models), some of them were zero-inflated quasipoisson due to the scoring rules of the survey. The statistical tests used were:

-   McNemar test for detecting if there is a change between the pre and post intervention.

-   Kruskal-Wallis test to identify if one socio-demographic characteristic is stochasticity superior to another one. This is also confirmed by the terms of the models built.

-   Chi-square and proportion test to inference when the frequency of an answer is different by socio-demographic characteristics.


#### Teacher

It sounds rare but during my bachelor's, I worked for almost 3 years as a teacher in a public primary school. I started during the pandemic when there was a huge lack of teachers and I took the opportunity!

It was a big challenge for me. I was in charge of teaching subjects such as math and science to children from 6 to 11 y.o. It taught me to manage a team of about 25 people (the students), very heterogeneous. Actually, I didn't learn only how to manage students, but also the other class teachers, as I was given the role of coordinator, handling all the bureaucratic stuff.

It was a really important part of my life where I learned (not only taught) a lot of soft skills about explaining hard concepts in an easy way (for the children is hard, trust me) and managing teams up to 25 people (and sometimes even parents ). In the meanwhile, I continued my studies so strategic planning of my life was the real key to success.

### Study

Here is a short overall about my studies:

-   Master's degree in Statistics and Actuarial Science with a curriculum in Data Science for Finance and Insurance at the University of Trieste.

-   Erasmus, during my master, at the University of Malaga (Spain) where the classes were in Spanish.

-   Bachelor's degree in Statistics and IT for Business, Finance, and Insurance, my thesis was focused on decisional tree models applied to the brewery industry.

So, my fields of study are mainly statistics, data science, actuarial science, IT, and finance.

## Personal Life

### Sport

I think that sport is very important in the life and helps to develop strength and health. Main sports:

-   Judo: From 4 y.o., I have done international competitions around Europe. In 2016, I went for 3 weeks for a training camp in Japan. But about Judo, I'm proud of my siblings who have achieved world results, as my brother was 3rd in the [World Judo Championship](https://www.ijf.org/judoka/50950) and 2nd in the European Judo Championship keeping the 1st place in the Juniors (U21) ranking -66Kg.

-   Run: I'm not very fast and not the best runner definitely. But I'm really proud about a personal challenge done in 2023, where I finished a trail of 57 Km without ever having ran more than 21 Km. It was quite mind-challenging.

-   Climbing: during my internship in Munich I discovered bouldering and when I came back, I started to climb outdoor: on the rock.

<!-- ### Travel

I could be boring on this point but it is the truth. I think that post-COVID most people changed their habits and I wasn't the exception. I've been to 20 countries, but some of them have been important for me:

-   Colombia: Follow my love and discover another one. That is the magic about travelling. I've lived for 3 months around this amazing country really different from what I expected.

-   Malaga (Spain): I'm sure that everyone who has done an exchange program (e.g. Erasmus) can agree with me, I Ieft a piece of my heart.

-   Sweden: It took place in my first Erasmus project and helped me to fight my fear for English, besides that I got the chance of meeting people from around Europe full of energy and positivity.

-   Marocco: I've been twice but why talking about the easy time with a touristic tour? Well, my girlfriend and I decided to take a random flight to the most unknown city, Nador, and what an adventure with no data and no local language during Ramadan. It has been a full immersion in the Arabic culture.

-   Houston (USA): I went to a wedding and I had the opportunity to live as a Texan for one week. -->

### Beer

I want to talk about the real beer: the craft one. I'm a nerd about craft beer, I brew my beer since 10 years ago and I use the BIAP method (Brew In A Pot). I love this hobby because it is a mix of creativity, science, and DIY. But I don't only make it, I also taste it and as a good statistician, I record each one on [Untapped](https://untappd.com/user/Erikdeluca)!
